/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    ListElement: typeof import('./src/components/ListElement.vue')['default']
    PizzaView: typeof import('./src/components/PizzaView.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    WBadge: typeof import('@waltz-ui/ui')['WBadge']
    WButton: typeof import('@waltz-ui/ui')['WButton']
    WCard: typeof import('@waltz-ui/ui')['WCard']
    WGrid: typeof import('@waltz-ui/ui')['WGrid']
    WIcon: typeof import('@waltz-ui/ui')['WIcon']
    TablePage: typeof import('./src/components/TablePage.vue')['default']
    TableView: typeof import('./src/components/TableView.vue')['default']
  }
}
