/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
import '@vue/runtime-core'

export {}

declare module '@vue/runtime-core' {
  export interface GlobalComponents {
    AeriaBox: typeof import('@waltz-ui/ui')['AeriaBox']
    AeriaButton: typeof import('@waltz-ui/ui')['AeriaButton']
    AeriaCard: typeof import('@waltz-ui/ui')['AeriaCard']
    AeriaForm: typeof import('@waltz-ui/ui')['AeriaForm']
    AeriaGrid: typeof import('@waltz-ui/ui')['AeriaGrid']
    AeriaInput: typeof import('@waltz-ui/ui')['AeriaInput']
    AeriaPanel: typeof import('@waltz-ui/ui')['AeriaPanel']
    EventView: typeof import('./src/components/event-view.vue')['default']
    PagePanel: typeof import('./src/components/page-panel.vue')['default']
    PizzaView: typeof import('./src/components/pizza-view.vue')['default']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TableView: typeof import('./src/components/table-view.vue')['default']
    WBox: typeof import('@waltz-ui/ui')['WBox']
    WButton: typeof import('@waltz-ui/ui')['WButton']
    WForm: typeof import('@waltz-ui/ui')['WForm']
  }
}
